server:
  port: 9002
  servlet:
    context-path: /poc
spring:
  security:
    user:
      name: poc
      password: poc123
      roles:
      - ADMIN
      - USER    
security:
  oauth2:
    client:
      client-id: poc-id
      client-secret: poc-secret
      access-token-validity-seconds: 3600
      authorized-grant-types:
      - refresh_token
      - authorization_code
      - password
      - client_credentials
      scope:
      - READ
      - WRITE
    authorization:
      check-token-access: permitAll